In [3]:
# Re-run this cell
import pandas as pd
import numpy as np

# Read in the data
schools = pd.read_csv("/content/drive/MyDrive/Datacamp/Project : Exploring NYC Public School Test Result Scores/schools.csv")

# Preview the data
schools.head()

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7

In [8]:
# 1. Finding schools with the best math scores

best_math_schools = schools[schools["average_math"] >= 640] [["school_name", "average_math"]].sort_values("average_math", ascending=False)

# best_math_schools = schools[schools["average_math"] >= (0.80 * 800)].sort_values("average_math", ascending=False)      ## Este fue mi codigo error : [["school_name", "average_math"]].sort_values

# 2. Identifying the top 10 performing schools

schools["total_SAT"] = schools["average_math"] + schools["average_reading"] + schools["average_writing"]

# best_math_schools["total_SAT"] = best_math_schools["average_math"] + best_math_schools["average_reading"] + best_math_schools["percent_tested"]

# 3. Who are the top 10 performing schools?

top_10_schools = schools.sort_values("total_SAT", ascending=False)[["school_name", "total_SAT"]].head(10)

# best_math_schools = best_math_schools.sort_values("total_SAT",ascending=False)

# 3.Locating the NYC borough with the largest standard deviation in SAT performance

# Which NYC borough has the highest standard deviation for total_SAT?

boroughs = schools.groupby("borough")["total_SAT"].agg(["count", "mean", "std"]).round(2)

# Filtering for the largest standard deviation

# 3.2 Filter for max std and make borough a column

largest_std_dev = boroughs[boroughs["std"] == boroughs["std"].max()]

# Renaming columns

# 3.3 Rename the columns for clarity

largest_std_dev = largest_std_dev.rename(columns={"count": "num_schools", "mean": "average_SAT", "std": "std_SAT"})

# Optional: Move borough from index to column

largest_std_dev.reset_index(inplace=True)